[project]
name = "RealTrainSimLowdham"
version = "1.1.0"
description = ""
authors = [{name = "Lowdham Railway Heritage"}]
requires-python = ">=3.13,<3.14"

dependencies = [
    "pyinstaller >= 6.15, < 7",
    "pytz >= 2025.1",
    "types-pytz >= 2025.2",
    "python-dotenv >= 1.1",
    "httpx >= 0.28",
    "stomp-py >=8.2",
    "docopt >= 0.6",
    "websocket-client >= 1.8",
]

[project.optional-dependencies]
dev = [
    "black >= 25.1, < 26",
    "mypy >= 1.14, < 2",
    "pre-commit >= 4.1, < 5",
    "psutil >= 6.1, < 7",
    "isort >= 6.0, < 7",
    "bump2version >= 1.0, < 2",
]

[tool.black]
line_length = 98

[tool.isort]
multi_line_output = 3
include_trailing_comma = true
force_grid_wrap = 0
use_parentheses = true
line_length = 98

#[build-system]
#requires = ["hatchling"]
#build-backend = "hatchling.build"
